### ISSUE TITLE
Захардкоженная ширина

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#10]
Не нужно в компонентах хардкодить ширину(особенно ставить фиксированную). Все манипуляции должна делать обертка над компонентом
![image](https://user-images.githubusercontent.com/47000555/101477530-27fe5880-3971-11eb-93db-37c5b9321bf8.png)
И тут та же ошибка, проверь по проекту и убери из компонентов ширину
![image](https://user-images.githubusercontent.com/47000555/101479211-a5c36380-3973-11eb-9a5a-06c5a1e2d8ce.png)
Из-за этого у тебя бесполезный модификатор, потому что у тебя ширина указана в самом компоненте.
![image](https://user-images.githubusercontent.com/47000555/101479395-f2a73a00-3973-11eb-8c00-39f167320dd3.png)

**Comment by wendivue** [comment]
Кнопки изменил, но не в обертки. Обертки не подходят для кнопок. 20 кнопок для них 20 оберток с одинаковым стилем. Еще 10 кнопок, которые отличаються по высоте еще 10 оберток. Дизайн меняется, основные кнопки уменьшаются на 3px и теперь нужно менять 20 оберток. А с модификаторами ты изменил одну строчку кода [bp](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.5)

**Comment by sodiqit** [comment]
Это спорный момент, конечно) Но здесь по-моему мнению это не критично впринципе)
