### ISSUE TITLE
Имена файлов

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#12]
Странное название, все файлы у тебя в стиле lower-case-hyphenated. А этот слитно.
![image](https://user-images.githubusercontent.com/47000555/101483867-9ac00180-397a-11eb-8875-e1be2634c5e1.png)

То же самое 
![image](https://user-images.githubusercontent.com/47000555/101483837-90056c80-397a-11eb-8c8d-4e0b029e4f59.png)

**Comment by wendivue** [comment]
> Checkbox-list.js 

Классы и функции-конструкторы называются с большой буквы, имена файлов соответственно, хотя может это вкусовщина)

**Comment by sodiqit** [comment]
Классы - верно. Файлы необязательно) обычно придерживаются одного стиля именования.

**Comment by sodiqit** [comment]
шрифты тоже нужно переименовать
