### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#13]
- в best practies отступ в css должен быть 2 пробела, у тебя 4. Следовательно лучше поправить и в html, чтобы код был консистентным.
- так же поправь названия переменных в которых содержится булево значение.
- в js обычно принято использовать одинарные ковычки, по сути здесь должны быть одинарные.
![image](https://user-images.githubusercontent.com/47000555/101481413-f6888b80-3976-11eb-9c52-b5105338492b.png)
 - так же пожалуйста не используй var, давным давно можно юзать let и const
 - одинарные ковычки 
![image](https://user-images.githubusercontent.com/47000555/101482383-78c57f80-3978-11eb-98f6-222f20f861e0.png)

**Comment by sodiqit** [comment]
camelCase
![image](https://user-images.githubusercontent.com/47000555/102687644-55b98c00-4212-11eb-9857-13df4bc1a044.png)

**Comment by sodiqit** [comment]
Можно обойтись без условия (класс можно добавить через тернарник). 
![image](https://user-images.githubusercontent.com/47000555/102688193-d4b0c380-4216-11eb-9474-0fd6d8cca2c4.png)

**Comment by sodiqit** [comment]
Имена переменных должны быть self-descriptive - тут же не очень ясно что это за переменные с первого взгляда. Это по идее классы, можно например menuSizeClassName, так сразу ясно что это модификатор размера для меню
![image](https://user-images.githubusercontent.com/47000555/102688576-5e619080-4219-11eb-9545-b31c21eb919a.png)

**Comment by sodiqit** [comment]
не нужно влиять на стили одного блока из другого
![image](https://user-images.githubusercontent.com/47000555/103135378-ba288f80-46d9-11eb-975a-5fa8b7645727.png)

**Comment by sodiqit** [comment]
перемести все медиа запросы в конец, так точно будешь знать что над ними все стили которые есть у класса
![image](https://user-images.githubusercontent.com/47000555/103135425-1390be80-46da-11eb-9305-fd26b2d413db.png)

**Comment by sodiqit** [comment]
camelCase
![image](https://user-images.githubusercontent.com/47000555/103136038-bc411d00-46de-11eb-9ba7-253cec08898b.png)

**Comment by sodiqit** [comment]
Все изменения в стилях, которые можно сделать через переключение классов у элемента, надо делать через добавление/удаление классов, а не простановку стилей у DOM-элементов.
![image](https://user-images.githubusercontent.com/47000555/103136083-28238580-46df-11eb-9a97-2e4a117e3938.png)

**Comment by sodiqit** [comment]
Ненужный класс у иконок, не вижу в нем смысла 
![image](https://user-images.githubusercontent.com/47000555/103136169-d6c7c600-46df-11eb-9fbc-41e35ad35092.png)

**Comment by wendivue** [comment]
> перемести все медиа запросы в конец, так точно будешь знать что над ними все стили которые есть у класса
> ![image](https://user-images.githubusercontent.com/47000555/103135425-1390be80-46da-11eb-9305-fd26b2d413db.png)

Если поставить это в конце, то будет не явное перезаписование. Допустим модификатор имеет другие стили на мобилке. Эти свойства перезаписались и теперь дефолтый блок и модификатор имеют одинаковое свойство, хотя ожидается что модификатор и на мобилке будет по другому выглядеть

**Comment by sodiqit** [comment]
Этот момент я не особо понял, я имею ввиду переместить медиа запросы в конец класса, чтобы под ними не было текущих стилей класса, о каком перезаписывании идет речь?

**Comment by sodiqit** [comment]
Добавь в лого ссылку на главную страницу

**Comment by sodiqit** [comment]
Нестрогое сравнение
![image](https://user-images.githubusercontent.com/47000555/105983965-4bb16580-60bb-11eb-988d-1b106c330b56.png)

**Comment by sodiqit** [comment]
Это один футер и он(маленький без текстовых столбцов) должен использоваться как мобильный
![image](https://user-images.githubusercontent.com/47000555/105985851-e14df480-60bd-11eb-9ac3-b7fb3b703538.png)

**Comment by sodiqit** [comment]
дублируются свойства
![image](https://user-images.githubusercontent.com/47000555/105989461-fda06000-60c2-11eb-992a-bc997053957a.png)

**Comment by sodiqit** [comment]
поправь пожалуйста стиль для задания модификаторов 
![image](https://user-images.githubusercontent.com/47000555/115110500-2e42b800-9f95-11eb-9fcc-139fb84c5cc7.png)
block__element_modifier
