### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#15]
Не работает eslint
![image](https://user-images.githubusercontent.com/47000555/101483402-f211a200-3979-11eb-942f-0343847286a8.png)
Поправь все замечания eslint'a
![image](https://user-images.githubusercontent.com/47000555/101483498-0ce41680-397a-11eb-8042-1b4530a9b083.png)

**Comment by wendivue** [comment]
Блин, не могу реализовать ошибку. Клонировал заново проект, у меня работает без ошибок
![Group 1](https://user-images.githubusercontent.com/23695919/102142665-89ad4e00-3eae-11eb-9d24-8e100b3a0dce.jpg)

**Comment by sodiqit** [comment]
Не работает снова eslint
![image](https://user-images.githubusercontent.com/47000555/105992390-dea3cd00-60c6-11eb-80a7-ff75a3efaca6.png)
Добавь в package.json скрипт для линтинга, чтобы в консоли было видно прошло проверку или нет

**Comment by sodiqit** [comment]
При проверке через команду еслинт цепляется к либам и их тоже проверяет из за этого в консоль сыпет ошибками)
![image](https://user-images.githubusercontent.com/47000555/115110448-eb80e000-9f94-11eb-9f25-c8f28804c386.png)
