### ISSUE TITLE
Файловая структура

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#17]
Странная структура, что за папка include? Я понимаю что ты хотел сделать шаблон страницы - layout, выносить такие штуки в отдельные компоненты тоже не очень
![image](https://user-images.githubusercontent.com/47000555/101484682-d14a4c00-397b-11eb-8c0c-47f355015ddf.png)

![image](https://user-images.githubusercontent.com/47000555/101484567-a6f88e80-397b-11eb-86a2-1abb9a7504a4.png)
Cделай просто папку отдельную layout в котором будут шаблон с нужными блоками - с хедером и футером и нужными col и тд. Просто толк от этого компонента не большой. 
Почитай про [наследование](https://pugjs.org/language/inheritance.html)

**Comment by wendivue** [comment]
Сорри за вот это, я просто тупой)) (в последнем изменение)
