### ISSUE TITLE
Dry

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#18]
У тебя на каждой странице подключается отдельно хедер с футером, повторяются одни и те же данные

**Comment by wendivue** [comment]
Исправление в issues #17 (общая проблема)

**Comment by sodiqit** [comment]
Лучше создать один миксин и туда параметрами скидывать названия шрифтов и тд
![image](https://user-images.githubusercontent.com/47000555/102688641-dc259c00-4219-11eb-8b91-068dcaf7786b.png)
