### ISSUE TITLE
Кастомизация

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#26]
Сейчас у тебя в некоторых компонентах прокидывается класс для кастомизации компонентов, что запрещено bp.
Просмотри по всему проекту такие моменты
![image](https://user-images.githubusercontent.com/47000555/102689363-442ab100-421f-11eb-89b8-3184e2e69b49.png)

**Comment by wendivue** [comment]
Не очень здесь понял почему нельзя (ссылка не работает)

**Comment by sodiqit** [comment]
[пункт 4.5](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.5)
