### ISSUE TITLE
Bundle

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#31]
1. Сейчас у тебя создается один огромный бандл, который грузится для каждой страницы, нужно сделать так, чтобы для каждой страницы подрубались нужные стили и скрипты. 
2. По-хорошему нужно добавить продакшн конфиг и для дева. Например, зачем подрубать минификатор в деве? Почему mode указан сразу production, его можно и желательно менять в зависимости от режима сборки.
3. Еще желательно добавить алиасы вместо относительных путей(во всех файлах, pug, scss, js), при смене файловой структуры, поменять нужно будет только путь в алиасе и ничего не сломается

**Comment by wendivue** [comment]
> 1. Сейчас у тебя создается один огромный бандл, который грузится для каждой страницы, нужно сделать так, чтобы для каждой страницы подрубались нужные стили и скрипты.

![Screenshot from 2021-04-05 00-40-57](https://user-images.githubusercontent.com/23695919/113534941-6224f180-9615-11eb-86f8-641bfacfa640.png)
Сейчас я собирает все js, scss файлы автоматом в этом js-e. 

Чтобы сделать для отдельной страницы - то что в голову пришло - это я поключаю для каждого страницы scss и js файлы, но всё руками. Я на правильном пути?

**Comment by sodiqit** [comment]
В принципе можно и так, но если хочешь пищу для размышлений, то можно автоматом искать точки входа в конкретной папке, например в папке pages, то есть при добавлении новой страницы, она будет автоматом подхватываться в точку входа. Если захочешь почитай про  `fs.readdirSync` На основе этой функции(node.js) ты сможешь написать кастомные функции для поиска всех файлов в указанной папке и цеплять их имена
