### ISSUE TITLE
Мелочи

### ISSUE THREAD

**Issue by Bibigyl** [wendivue/template-toxin#46]
Не тот шрифт 
![image](https://user-images.githubusercontent.com/44343944/125446062-2acc2380-cfd0-4612-b275-589c5b9d2b2a.png)

Цифры немного не по центру
![image](https://user-images.githubusercontent.com/44343944/125446315-a1351355-12c5-4502-8a0f-759b282acd86.png)

1 твое, 2 макет. Сверху тоже отступ маленький
![image](https://user-images.githubusercontent.com/44343944/125446523-fce55166-720c-4076-8f1a-a4102e0b207d.png)
![image](https://user-images.githubusercontent.com/44343944/125446670-31c88739-f996-4c6d-b040-a2a995705b22.png)

Проверь cursor pinter на range slider. Он есть там на пустом поле

Скругли уголки
![image](https://user-images.githubusercontent.com/44343944/125447152-7a65b3a7-2e78-4e9a-918e-f3305b3ae9b2.png)

**Comment by Bibigyl** [comment]
выравнивание текста по центру
![image](https://user-images.githubusercontent.com/44343944/125450512-a38234da-c76a-4840-99c1-3f29edb30f39.png)

**Comment by Bibigyl** [comment]
![Peek 2021-07-13 15-22](https://user-images.githubusercontent.com/44343944/125450785-e888ef02-9d79-4470-a0bf-e40a156fbe00.gif)

если получится, поправь, ширина немного скачет

**Comment by Bibigyl** [comment]
Левая кнопка подсвечена на ховер, правая нет. Нужно привести все к одному виду. 
Сейчас в макете указано что все кнопки  фиолетовый, а на ховер серые. Если у тебя старый макет, оставь как есть
![Peek 2021-07-13 15-26](https://user-images.githubusercontent.com/44343944/125451289-ba428ea6-c38c-458f-87fb-fd6b8ac90388.gif)

**Comment by kate-fsd** [comment]
js-dropdown__button дублируется

**Comment by kate-fsd** [comment]
Не хватает теней
![image](https://user-images.githubusercontent.com/66846004/131879011-55d809d8-b2df-4bdc-a85e-070d3b52c131.png)

**Comment by kate-fsd** [comment]
Теперь не меняется обводка
![image](https://user-images.githubusercontent.com/66846004/131880365-41bf421c-4940-41f3-ac60-bcefbd813384.png)

**Comment by kate-fsd** [comment]
Лучше либо весь диапазон сделать фиолетовым либо на последней дате зеленым
![image](https://user-images.githubusercontent.com/66846004/131882507-061f3e49-6496-4b32-b2ab-32a51ba51806.png)

**Comment by kate-fsd** [comment]
кружок не по центру по вертикали
![image](https://user-images.githubusercontent.com/66846004/131882820-ef74f576-7621-404b-9cbb-36a39b8f82f5.png)

**Comment by kate-fsd** [comment]
Все фоновые картинки выровнены по правому краю. Лучше выровнять по центру

**Comment by kate-fsd** [comment]
Выровнять значение в лайке по вертикали
![image](https://user-images.githubusercontent.com/66846004/131883825-524b6444-e04f-41c6-b3b3-836c6fe9a4a2.png)

**Comment by kate-fsd** [comment]
линии короче чем в макете
![image](https://user-images.githubusercontent.com/66846004/131884130-b0c6a04d-d03b-401e-9b4c-d88479d87d7e.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/131884630-b278a497-2237-43ed-992c-4def000bcd4d.png)

**Comment by kate-fsd** [comment]
Страница room-details. Нужно поднять форму выше. Обычно сначала на странице видна важная информация, а ниже второстепенная, вроде отзывов, описании и тд

**Comment by kate-fsd** [comment]
> 1 твое, 2 макет. Сверху тоже отступ маленький
> ![image](https://user-images.githubusercontent.com/44343944/125446523-fce55166-720c-4076-8f1a-a4102e0b207d.png)

На странице room-details так
![image](https://user-images.githubusercontent.com/66846004/131886363-a14573c2-2e7d-4743-8fc3-aa71923b6c0f.png)

А на лэндинг так
![image](https://user-images.githubusercontent.com/66846004/131886446-4debb683-0b07-440f-bea1-8053d7428e7a.png)

И то что они на разных страницах выглядят по разному скорее всего говорит об ошибке
