### ISSUE TITLE
Masked text field

### ISSUE THREAD

**Issue by Bibigyl** [wendivue/template-toxin#48]
![image](https://user-images.githubusercontent.com/44343944/125450280-9168190b-2e3a-4aea-be6f-adb3898c74f7.png)

Text field - это поле ввода текста. То есть текст нужно ввести с клавиатуры
Masked значит что на этом поле ввода есть маска, которая позволит ввести текст только по определенному шаблону, без лишних символов
На скрине пример маски даты. Будет хорошо, если помимо маски даты можно будет применить и другие. Параметры маски можно передать из pug в js с помощью дата атрибутов

**Comment by kate-fsd** [comment]
Не работает маска
![image](https://user-images.githubusercontent.com/66846004/131883276-7cfc71d5-b11d-45d5-8572-f1b47a15fd31.png)

**Comment by wendivue** [comment]
тоже что и в 58

**Comment by kate-fsd** [comment]
Нужно сделать маску такого же шаблона, что в макете. То есть с точками
