### ISSUE TITLE
Пончик

### ISSUE THREAD

**Issue by kate-fsd** [wendivue/template-toxin#54]
Пончик не должен быть просто картинкой. В параметрах нужно передать список значении, подписей, цветов и построить круговую диаграмму на их основе

**Comment by kate-fsd** [comment]
Число в центре лучше не передавать отдельно, а суммировать. И проблема с цветами
![image](https://user-images.githubusercontent.com/66846004/131907408-252671fd-8fd5-4798-bed7-bdb86ebc2837.png)
Передаю
        "votes": 1000,
        "colorFirst": "red",
        "colorSecond": "orange"

**Comment by kate-fsd** [comment]
Если ты передаешь цвета в параметрах то в css они тебе не нужны

**Comment by wendivue** [comment]
> И проблема с цветами

Проблема с цветом решиться в #58 

> Передаю
> "votes": 1000,
> "colorFirst": "red",
> "colorSecond": "orange"

![Screenshot from 2021-09-03 14-59-59](https://user-images.githubusercontent.com/23695919/131954811-ff2d4bee-d1e2-4b0a-bcac-b62e1bb22f75.png)

**Comment by kate-fsd** [comment]
mixin pie-chart({ votesText, list })
В этом учебном проекте лучше сделать компоненты максимально универсальными и заменить привязку к votes на что то обезличенное - просто items. По жалению
