### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by sodiqit** [wendivue/template-toxin#9]
- Неправильное использование заголовка(зачем их 2?)
![image](https://user-images.githubusercontent.com/47000555/101477045-78c18180-3970-11eb-8bf8-c76962321c78.png)
- Неправильное использование ссылок и кнопок, конкректно это - кнопка, а у тебя есть только возможность создавать ссылки в твоем компоненте button. Все что ведет на другую страницу - ссылка, остальное - кнопка. 
![image](https://user-images.githubusercontent.com/47000555/101478709-eb336100-3972-11eb-9863-db6b31d67708.png)
- Неиспользование списка когда он явно нужен
![image](https://user-images.githubusercontent.com/47000555/101482059-ee7d1b80-3977-11eb-8e35-6fe8f40f8863.png)
- Кнопка
![image](https://user-images.githubusercontent.com/47000555/101484028-ce029080-397a-11eb-9f11-bb9914fcccec.png)

**Comment by sodiqit** [comment]
Это тоже список
![image](https://user-images.githubusercontent.com/47000555/102687597-fbb8c680-4211-11eb-9563-d5cc56f899a5.png)

**Comment by sodiqit** [comment]
бесполезные два h2 подряд(можно один сделать просто)
![image](https://user-images.githubusercontent.com/47000555/102688737-6ff76800-421a-11eb-89fe-d5644f437080.png)

**Comment by sodiqit** [comment]
Тут семантически лучше что-то типо h3 
![image](https://user-images.githubusercontent.com/47000555/102689175-e9448a00-421d-11eb-9ab6-e856bcb641c1.png)

**Comment by sodiqit** [comment]
Поля в формах должны иметь обоснованный тип, а не просто text.

**Comment by sodiqit** [comment]
У тебя имеется очень сомнительный header в чекбоксах 
![image](https://user-images.githubusercontent.com/47000555/103135720-02e14800-46dc-11eb-9196-57711589073b.png)
Чем тут отличаются элементы? Только в первых двух используется header, а в третьем варианте нет. Лучше его убрать
Так еще и тут нет заголовка 
![image](https://user-images.githubusercontent.com/47000555/103135755-5fdcfe00-46dc-11eb-9a9e-3eb202b967fd.png)

**Comment by sodiqit** [comment]
В списке у тебя лежит div, его нужно вынести из списка
![image](https://user-images.githubusercontent.com/47000555/103135796-c6621c00-46dc-11eb-8b32-c8abbe8601ff.png)

**Comment by sodiqit** [comment]
У тебя есть хедер для чекбоксов, но нет для самого хедера)
![image](https://user-images.githubusercontent.com/47000555/103135863-6455e680-46dd-11eb-8b57-f99bf466b08f.png)
Аналогично для футера

**Comment by sodiqit** [comment]
еще не увидел у тебя ни одного тега section, все на дивах, хотя на сайте выражены разные секции, добавив их ты улучшишь доступность сайта

**Comment by sodiqit** [comment]
У инпутов не вижу имени, оно нужно чтобы удобней отправлять данные на сервак

**Comment by wendivue** [comment]
> Так еще и тут нет заголовка
там label

**Comment by sodiqit** [comment]
https://user-images.githubusercontent.com/47000555/105981777-4b639b00-60b8-11eb-9282-12d0bcc31c6a.mp4
Не работает label. Вообще, по-хорошему если label лежит рядом с input'ом, то лучше инпут вложить в лейбл без id

**Comment by sodiqit** [comment]
label
![image](https://user-images.githubusercontent.com/47000555/105984474-faee3c80-60bb-11eb-9a76-0bc37bbb4ded.png)

**Comment by sodiqit** [comment]
Это тоже список 
![image](https://user-images.githubusercontent.com/47000555/105985176-f37b6300-60bc-11eb-8abf-3162ca1ad762.png)

**Comment by sodiqit** [comment]
Почему тут список из трех элементов только? По сути это один большой список карточек
![image](https://user-images.githubusercontent.com/47000555/105989819-77384e00-60c3-11eb-9310-b569566a2dd9.png)

**Comment by wendivue** [comment]
> Вообще, по-хорошему если label лежит рядом с input'ом, то лучше инпут вложить в лейбл без id

Я сделал так, потому что  вложенный инпут влияет на поведение обертывания и лейбл являеться контейнером, что порой не очень хочется, особенно когда они далеко друг от друга визуально, но в DOM-e они рядом

**Comment by sodiqit** [comment]
а что ты имеешь ввиду под `влияет на поведение обертывания`?

**Comment by wendivue** [comment]
Не правильно выразился - *разница в поведении.  Когда инпут внутри лейбла, пространство между инпутом и лейбл кликабельно
